
spring:
  datasource:
    url: HIDDEN
    username: HIDDEN
    password: HIDDEN
  jpa:
    hibernate:
      ddl-auto: update

security:
  oauth2:
    client:
      clientId: HIDDEN
      clientSecret: HIDDEN
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

oauthKey: HIDDEN

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
